name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Buildozer and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libsqlite3-dev libreadline-dev libffi-dev libssl-dev
        # Оновлюємо aclocal, щоб він не сварився на старі макроси libffi
        autoreconf -ivf || true
        pip install --upgrade p
        pip install --upgrade pip
        pip install --user --upgrade buildozer cython
        pip install --user --upgrade git+https://github.com/kivy/python-for-android.git
        
    - name: Build with Buildozer
      env:
        ANDROID_NDK_ROOT: /home/runner/.buildozer/android/platform/android-ndk-r25c
        ANDROID_NDK: /home/runner/.buildozer/android/platform/android-ndk-r25c
      run: |
        export PATH=$PATH:~/.local/bin
        export P4A_ANDROID_SDK_ACCEPT_LICENSE=1
        buildozer --accept-all --debug android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: |
          bin/*.apk
          /**/*.apk
          
          
